<a href="https://colab.research.google.com/github/Nishanthini03/AI_Inetrnship/blob/main/AI_P1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector, Matrix and Tensor

In [ ]:
import numpy as np
vector = np.array([1,2,3])  #1D
matrix = np.array([[1,2,3], [4,5,6]]) #2D
tensor = np.array([[[1,2,3], [1,2,3]], [[4,5,6], [4,5,6]]]) #3D(two matrices with size of 2x3)

print("Vector \n", vector)
print("\nMatrix \n", matrix)
print(f"\n Tensor \n{tensor}\n")
print(f"Shape of vector: {vector.shape}")
print(f"Shape of matrix: {matrix.shape}")
print(f"Shape of tensor: {tensor.shape}")
print(f"Number of dimensions of tensor: {tensor.ndim}")
print(f"Total number of elements in the tensor: {tensor.size}")
print(f"Change shape of tensor: \n{tensor.reshape(4,3)}")
print("\nTotal Sum:", np.sum(tensor))
print("\nSum Across First Axis:\n", np.sum(tensor, axis=0))
print("\nSum Across Second Axis:\n", np.sum(tensor, axis=1))
print("\nSum Across Third Axis:\n", np.sum(tensor, axis=2))
print("\nMean Across First Axis:\n", np.mean(tensor, axis=0))
print("\nMean Across Second Axis:\n", np.mean(tensor, axis=1))
print("\nMean Across Third Axis:\n", np.mean(tensor, axis=2))
# Accessing the first matrix
print("\nFirst Matrix:\n", tensor[0])

# Accessing a specific element (Row 2, Column 3 of Matrix 1)
print("\nElement at [0, 1, 2]:", tensor[0, 1, 2])  # Output: 7


Vector 
 [1 2 3]

Matrix 
 [[1 2 3]
 [4 5 6]]

 Tensor 
[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]

Shape of vector: (3,)
Shape of matrix: (2, 3)
Shape of tensor: (2, 2, 3)
Number of dimensions of tensor: 3
Total number of elements in the tensor: 12
Change shape of tensor: 
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]

Total Sum: 42

Sum Across First Axis:
 [[5 7 9]
 [5 7 9]]

Sum Across Second Axis:
 [[ 2  4  6]
 [ 8 10 12]]

Sum Across Third Axis:
 [[ 6  6]
 [15 15]]

Mean Across First Axis:
 [[2.5 3.5 4.5]
 [2.5 3.5 4.5]]

Mean Across Second Axis:
 [[1. 2. 3.]
 [4. 5. 6.]]

Mean Across Third Axis:
 [[2. 2.]
 [5. 5.]]

First Matrix:
 [[1 2 3]
 [1 2 3]]

Element at [0, 1, 2]: 3


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

sum_matrix = A + B
prod_matrix = A @ B  # Matrix multiplication
transposed = A.T  # Transpose
inverse_A = np.linalg.inv(A)  # Inverse of A

print("Sum of Matrices:\n", sum_matrix)
print("Matrix Product:\n", prod_matrix)
print("Transpose of A:\n", transposed)
print("Inverse of A:\n", inverse_A)

Sum of Matrices:
 [[ 6  8]
 [10 12]]
Matrix Product:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
v1 = np.array([2, 3, 4])
v2 = np.array([1, 0, -1])
dot_product = np.dot(v1, v2)
print("Dot Product:", dot_product)

Dot Product: -2


In [ ]:
random_tensor = np.random.randint(1, 100, (2, 3, 4))  # Random integers from 1 to 99
print("\nRandom 3D Tensor:\n", random_tensor)


Random 3D Tensor:
 [[[16 60 40 39]
  [87 59 24 37]
  [ 7 97 82 89]]

 [[98 78 39 28]
  [22 67 53 85]
  [95 11 19 46]]]


Transpose

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original Matrix:\n", matrix)

# Transpose the matrix
matrix_T = np.transpose(matrix)
print("\nTransposed Matrix:\n", matrix_T)
print(matrix.T)  # Same result

tensor = np.array([
    [[1, 2], [3, 4]],  # First 2x2 matrix
    [[5, 6], [7, 8]]   # Second 2x2 matrix
])

print("Original Tensor Shape:", tensor.shape)  # (2, 2, 2)

# Transpose with axes (1, 0, 2)
tensor_T = np.transpose(tensor, (1, 0, 2))
#1 moves to the first position → Rows become the first dimension.
#0 moves to the second position → Depth becomes the second dimension.
#2 stays in the same position → Columns remain unchanged.
#First matrix becomes: Row 1 from all previous matrices
#Second matrix becomes: Row 2 from all previous matrices
print("\nTransposed Tensor Shape:", tensor_T.shape)
print("\nTransposed Tensor(1, 0, 2):\n", tensor_T)

transposed_tensor = np.transpose(tensor, (2, 1, 0))
print("\nTransposed Tensor Shape:", transposed_tensor.shape)  # Output: (2,2,2)
print("\nTransposed Tensor(2, 1, 0):\n", transposed_tensor)
#First matrix: Column 1 from all previous matrices
#Second matrix: Column 2 from all previous matrices

transposed_tensor1 = np.transpose(tensor, (0, 2, 1))
#Swapping rows and columns for each matrix
print("\nTransposed Tensor Shape:", transposed_tensor1.shape)  # Output: (2,2,2)
print("\nTransposed Tensor(0, 2, 1):\n", transposed_tensor1)


Original Matrix:
 [[1 2 3]
 [4 5 6]]

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
Original Tensor Shape: (2, 2, 2)

Transposed Tensor Shape: (2, 2, 2)

Transposed Tensor(1, 0, 2):
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]

Transposed Tensor Shape: (2, 2, 2)

Transposed Tensor(2, 1, 0):
 [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]

Transposed Tensor Shape: (2, 2, 2)

Transposed Tensor(0, 2, 1):
 [[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


Eigenvalues and Eigenvectors

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
